#! /bin/bash

jid1=$(sbatch Runtask|sed 's/Submitted batch job //')
echo "Running on hosts: $jid1  !"
jid2=$(sbatch --dependency=afterany:$jid1 srun|sed 's/Submitted batch job //')

squeue -u $USER -o "%.8A %.4C %.10m %.20E"