#!/bin/bash
#
#SBATCH --job-name=graph            
#SBATCH --nodes=1
#SBATCH --tasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --time=04:00:00
#SBATCH --output=./stdout/slurm-%j.out


srun python3 ./pic.py